package bd.ac.uiu.smartcampus.controller;

import bd.ac.uiu.smartcampus.dto.ApiResponse;
import bd.ac.uiu.smartcampus.dto.CampusTelemetryDto;
import bd.ac.uiu.smartcampus.model.AdminActionLog;
import bd.ac.uiu.smartcampus.model.CampusState;
import bd.ac.uiu.smartcampus.model.MaintenanceComplaint;
import bd.ac.uiu.smartcampus.model.EquipmentBooking;
import bd.ac.uiu.smartcampus.service.StudentPortalService;
import bd.ac.uiu.smartcampus.security.CustomUserDetails;
import bd.ac.uiu.smartcampus.syllabus.collections.AdminActionStackService;
import bd.ac.uiu.smartcampus.syllabus.collections.ComplaintQueueService;
import bd.ac.uiu.smartcampus.syllabus.collections.UniqueAttendeeSetService;
import bd.ac.uiu.smartcampus.syllabus.concurrency.CampusSimulationWorker;
import bd.ac.uiu.smartcampus.syllabus.fileio.CampusLogFileWriter;
import bd.ac.uiu.smartcampus.syllabus.fileio.CampusStateBackupService;
import bd.ac.uiu.smartcampus.syllabus.networking.BusClientSimulator;
import bd.ac.uiu.smartcampus.syllabus.networking.BusServerSocketManager;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/campus")
public class CampusApiController {

    private final CampusSimulationWorker simulationWorker;
    private final AdminActionStackService actionStackService;
    private final ComplaintQueueService complaintQueueService;
    private final UniqueAttendeeSetService attendeeSetService;
    private final CampusLogFileWriter logFileWriter;
    private final CampusStateBackupService backupService;
    private final BusServerSocketManager busServerManager;
    private final BusClientSimulator busClientSimulator;
    private final StudentPortalService studentPortalService;

    public CampusApiController(CampusSimulationWorker simulationWorker,
                               AdminActionStackService actionStackService,
                               ComplaintQueueService complaintQueueService,
                               UniqueAttendeeSetService attendeeSetService,
                               CampusLogFileWriter logFileWriter,
                               CampusStateBackupService backupService,
                               BusServerSocketManager busServerManager,
                               BusClientSimulator busClientSimulator,
                               StudentPortalService studentPortalService) {
        this.simulationWorker = simulationWorker;
        this.actionStackService = actionStackService;
        this.complaintQueueService = complaintQueueService;
        this.attendeeSetService = attendeeSetService;
        this.logFileWriter = logFileWriter;
        this.backupService = backupService;
        this.busServerManager = busServerManager;
        this.busClientSimulator = busClientSimulator;
        this.studentPortalService = studentPortalService;
    }

    /**
     * Get live campus telemetry generated by background worker thread
     */
    @GetMapping("/telemetry")
    public ApiResponse<CampusTelemetryDto> getLiveTelemetry() {
        return ApiResponse.ok("Live telemetry snapshot", simulationWorker.getLatestTelemetry());
    }

    /**
     * AOOP Stack: Record action (Push to Stack)
     */
    @PostMapping("/admin/action")
    public ApiResponse<AdminActionLog> recordAdminAction(@RequestParam String actionType,
                                                         @RequestParam String details,
                                                         @RequestParam(defaultValue = "admin-demo") String email) {
        AdminActionLog log = actionStackService.recordAction(email, actionType, details);
        logFileWriter.appendAuditLog("ADMIN_STACK_PUSH", actionType + ": " + details);
        return ApiResponse.ok("Pushed to Admin Action Stack (LIFO)", log);
    }

    /**
     * AOOP Stack: Undo last action (Pop from Stack)
     */
    @PostMapping("/admin/undo")
    public ApiResponse<AdminActionLog> undoLastAction() {
        AdminActionLog popped = actionStackService.undoLastAction();
        if (popped != null) {
            logFileWriter.appendAuditLog("ADMIN_STACK_POP", "Undid action: " + popped.getActionType());
            return ApiResponse.ok("Popped and undid top action from Stack (LIFO)", popped);
        }
        return ApiResponse.error("Admin action stack is empty");
    }

    /**
     * AOOP Queue: Enqueue new maintenance complaint (FIFO Offer)
     */
    @PostMapping("/complaint/submit")
    public ApiResponse<MaintenanceComplaint> submitComplaint(@RequestBody MaintenanceComplaint complaint,
                                                             @AuthenticationPrincipal CustomUserDetails userDetails) {
        if (complaint.getIssueTitle() == null || complaint.getIssueTitle().isBlank()) {
            return ApiResponse.error("Issue title is required.");
        }
        if (complaint.getLocation() == null || complaint.getLocation().isBlank()) {
            return ApiResponse.error("Location is required.");
        }
        applyReporterIdentity(complaint, userDetails);
        MaintenanceComplaint queued = complaintQueueService.submitComplaint(complaint);
        logFileWriter.appendAuditLog("QUEUE_ENQUEUE", "Complaint queued: " + complaint.getIssueTitle());
        return ApiResponse.ok("Complaint enqueued in FIFO Processing Queue", queued);
    }

    /**
     * AOOP Queue: Process next complaint (FIFO Poll)
     */
    @PostMapping("/complaint/process-next")
    public ApiResponse<MaintenanceComplaint> processNextComplaint() {
        MaintenanceComplaint resolved = complaintQueueService.processNextComplaint();
        if (resolved != null) {
            logFileWriter.appendAuditLog("QUEUE_DEQUEUE", "Resolved complaint: " + resolved.getIssueTitle());
            return ApiResponse.ok("Processed next complaint from head of FIFO Queue", resolved);
        }
        return ApiResponse.error("Complaint queue is currently empty");
    }

    /**
     * AOOP Set: Gate check-in (prevents duplicates)
     */
    @PostMapping("/gate/checkin")
    public ApiResponse<String> checkInStudent(@RequestParam String studentId) {
        boolean added = attendeeSetService.checkInStudent(studentId);
        if (added) {
            logFileWriter.appendAuditLog("SET_CHECKIN", "New unique check-in: " + studentId);
            return ApiResponse.ok("Access granted: Student " + studentId + " checked in (Set size: " + attendeeSetService.getUniqueCount() + ")");
        } else {
            return ApiResponse.error("Duplicate notice: Student " + studentId + " is ALREADY recorded in the unique attendee Set");
        }
    }

    /**
     * AOOP File I/O: Create serialized binary backup (ObjectOutputStream)
     */
    @PostMapping("/backup/save")
    public ApiResponse<String> backupCampusState() {
        CampusTelemetryDto tel = simulationWorker.getLatestTelemetry();
        CampusState state = new CampusState(
                "United International University (UIU)",
                tel.getActiveStudents(),
                tel.getFacultyOnCampus(),
                tel.getTotalRooms(),
                tel.getOccupiedRooms(),
                tel.getPowerConsumptionKW(),
                tel.getSystemStatus()
        );
        boolean saved = backupService.backupCampusState(state);
        if (saved) {
            logFileWriter.appendAuditLog("SERIALIZATION", "Campus state serialized to binary backup file");
            return ApiResponse.ok("CampusState object serialized successfully to campus_state_snapshot.dat via ObjectOutputStream!");
        }
        return ApiResponse.error("Failed to serialize campus state backup");
    }

    /**
     * AOOP File I/O: Restore serialized binary backup (ObjectInputStream)
     */
    @GetMapping("/backup/restore")
    public ApiResponse<CampusState> restoreCampusState() {
        CampusState state = backupService.restoreCampusState();
        if (state != null) {
            return ApiResponse.ok("CampusState object restored from disk via ObjectInputStream", state);
        }
        return ApiResponse.error("No backup snapshot file found on disk");
    }

    /**
     * AOOP File I/O: Read recent text audit logs (FileReader)
     */
    @GetMapping("/logs")
    public ApiResponse<List<String>> getAuditLogs(@RequestParam(defaultValue = "15") int limit) {
        List<String> logs = logFileWriter.readRecentAuditLogs(limit);
        return ApiResponse.ok("Retrieved " + logs.size() + " audit log entries via FileReader", logs);
    }

    /**
     * AOOP Networking: Transmit GPS coordinate via TCP Socket to ServerSocket
     */
    @PostMapping("/bus/transmit")
    public ApiResponse<String> transmitBusTelemetry(@RequestParam String busId, @RequestParam String location) {
        String response = busClientSimulator.sendBusLocationUpdate(busId, location);
        return ApiResponse.ok("Bus Socket Transmission result: " + response);
    }

    /**
     * Get latest bus positions
     */
    @GetMapping("/bus/locations")
    public ApiResponse<Map<String, String>> getBusLocations() {
        return ApiResponse.ok("Active bus routes", busServerManager.getLatestBusLocations());
    }

    /**
     * Admin Equipment & Lab Checkout Management
     */
    @GetMapping("/admin/equipment/bookings")
    public ApiResponse<List<EquipmentBooking>> getAllEquipmentBookings() {
        return ApiResponse.ok("All student equipment bookings", studentPortalService.getAllBookings());
    }

    @PostMapping("/admin/equipment/bookings/{id}/status")
    public ApiResponse<EquipmentBooking> updateEquipmentBookingStatus(
            @PathVariable Long id,
            @RequestParam String status,
            @RequestParam(required = false, defaultValue = "") String remarks,
            @AuthenticationPrincipal CustomUserDetails userDetails) {
        String adminEmail = userDetails != null ? userDetails.getUsername() : "admin-demo";
        EquipmentBooking.BookingStatus bookingStatus = EquipmentBooking.BookingStatus.valueOf(status.toUpperCase());
        EquipmentBooking updated = studentPortalService.updateBookingStatus(id, bookingStatus, remarks);

        // Record action to AOOP Admin Action Stack
        actionStackService.recordAction(adminEmail, "EQUIPMENT_BOOKING_" + bookingStatus.name(),
                "Updated booking #" + id + " for " + updated.getStudentName() + " to " + bookingStatus.name());
        logFileWriter.appendAuditLog("EQUIPMENT_BOOKING_REVIEW",
                "Booking #" + id + " updated to " + bookingStatus.name() + " by " + adminEmail);

        return ApiResponse.ok("Equipment booking status updated to " + bookingStatus.name(), updated);
    }

    private void applyReporterIdentity(MaintenanceComplaint complaint, CustomUserDetails userDetails) {
        String reporterName = userDetails != null ? userDetails.getFullName() : "Authenticated User";
        String reporterId = userDetails != null && userDetails.getStudentOrEmpId() != null && !userDetails.getStudentOrEmpId().isBlank()
                ? userDetails.getStudentOrEmpId()
                : userDetails != null ? userDetails.getUsername() : "unknown";
        String reporterRole = userDetails != null ? userDetails.getRoleName() : "UNKNOWN";

        complaint.setReporterName(reporterName);
        complaint.setReporterId(reporterId);
        complaint.setReporterRole(reporterRole);

        // Legacy fields remain populated so existing Student/Admin screens and repository queries keep working.
        complaint.setStudentName(reporterName);
        complaint.setStudentId(reporterId);
    }
}
